import { TemplateMetadata } from './canvasEngine';
import { viralHook }          from './templates/viralHook';
import { editorialMagazine }  from './templates/editorialMagazine';
import { cleanWhite }         from './templates/cleanWhite';
import { minimalDark }        from './templates/minimalDark';
import { magnataSplit }       from './templates/magnataSplit';
import { cardFloat }          from './templates/cardFloat';
import { dataInsight }        from './templates/dataInsight';
import { analistaCraft }      from './templates/analistaCraft';
import { splitStatement }     from './templates/splitStatement';
import { iosNotification }    from './templates/iosNotification';

import { newsG1 }             from './templates/newsG1';
import { tweetSocial }        from './templates/tweetSocial';
import { appleMinimal }       from './templates/appleMinimal';
import { glassNeon }          from './templates/glassNeon';
import { listicleProgress }   from './templates/listicleProgress';
import { mockupPhone }        from './templates/mockupPhone';
import { legalClassic }       from './templates/legalClassic';

export const TEMPLATE_REGISTRY: TemplateMetadata[] = [
  {
    id: 'listicle-progress',
    name: 'Listicle & Progress',
    category: 'editorial',
    previewGradient: 'linear-gradient(135deg, #111116 0%, #303038 100%)',
    previewAccent: '#7C3AED',
    renderer: listicleProgress,
    supportedFormats: ['square', 'portrait', 'landscape'],
    imageSuggested: false,
    description: 'Estilo checklist ou passo a passo. Ideal para tutoriais e carrosséis longos.',
  },
  {
    id: 'mockup-phone',
    name: 'Mockup Phone',
    category: 'bold',
    previewGradient: 'linear-gradient(135deg, #7C3AED 0%, #5d2bbb 100%)',
    previewAccent: '#fff',
    renderer: mockupPhone,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: true,
    description: 'Simula uma notificação ou conteúdo dentro de um celular fictício.',
  },
  {
    id: 'legal-classic',
    name: 'Jurídico Classic',
    category: 'minimal',
    previewGradient: 'linear-gradient(135deg, #0F172A 0%, #1e293b 100%)',
    previewAccent: '#D4AF37',
    renderer: legalClassic,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Sóbrio, focado em texto e com elementos de moldura clássica (cores ouro/navy).',
  },
  {
    id: 'glass-neon',
    name: 'Glass & Neon',
    category: 'bold',
    previewGradient: 'linear-gradient(135deg, #111 0%, #333 100%)',
    previewAccent: '#00ffcc',
    renderer: glassNeon,
    supportedFormats: ['square', 'portrait', 'landscape'],
    imageSuggested: true,
    description: 'Painel flutuante ultra-premium com bordas neon suaves. Ideal para leitura Z-Pattern.',
  },
  {
    id: 'news-g1',
    name: 'G1 Notícia',
    category: 'editorial',
    previewGradient: 'linear-gradient(135deg, #CC0000 0%, #aa0000 100%)',
    previewAccent: '#fff',
    renderer: newsG1,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: true,
    description: 'Estilo plantão de portal de notícias.',
  },
  {
    id: 'tweet-social',
    name: 'X (Tweet)',
    category: 'social',
    previewGradient: 'linear-gradient(135deg, #1DA1F2 0%, #0d8bd9 100%)',
    previewAccent: '#fff',
    renderer: tweetSocial,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: true,
    description: 'Simula um post viral no X (antigo Twitter).',
  },
  {
    id: 'apple-minimal',
    name: 'Minimal',
    category: 'minimal',
    previewGradient: 'linear-gradient(135deg, #fbfbfd 0%, #e0e0e0 100%)',
    previewAccent: '#1d1d1f',
    renderer: appleMinimal,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: true,
    description: 'Ultra minimalista e hiper-premium. Menos é mais.',
  },
  {
    id: 'viral-hook',
    name: 'Viral Hook',
    category: 'bold',
    previewGradient: 'linear-gradient(135deg, #09090F 0%, #3b1170 100%)',
    previewAccent: '#fff',
    renderer: viralHook,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: true,
    description: 'Texto gigante sobre fundo escuro. Máximo impacto.',
  },
  {
    id: 'split-statement',
    name: 'Split Statement',
    category: 'bold',
    previewGradient: 'linear-gradient(90deg, #1a1a2e 50%, #7C3AED 50%)',
    previewAccent: '#fff',
    renderer: splitStatement,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: true,
    description: '50% imagem | 50% cor sólida com texto.',
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial',
    category: 'editorial',
    previewGradient: 'linear-gradient(to top, #000 0%, rgba(0,0,0,0.3) 50%, transparent 100%), linear-gradient(135deg, #1a1a2e, #2d1b69)',
    previewAccent: '#fff',
    renderer: editorialMagazine,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: true,
    description: 'Estilo capa de revista. Headline na base.',
  },
  {
    id: 'magnata-split',
    name: 'Magnata',
    category: 'editorial',
    previewGradient: 'linear-gradient(135deg, #0d0d0d 0%, #1a1000 100%)',
    previewAccent: '#c9a962',
    renderer: magnataSplit,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Luxo dark com detalhes dourados. Playfair.',
  },
  {
    id: 'analista-craft',
    name: 'Craft',
    category: 'editorial',
    previewGradient: 'linear-gradient(135deg, #f5f0e6 0%, #e8dcc8 100%)',
    previewAccent: '#1C1C1C',
    renderer: analistaCraft,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Jornalístico e investigativo. Textura de papel.',
  },
  {
    id: 'clean-white',
    name: 'Clean White',
    category: 'minimal',
    previewGradient: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)',
    previewAccent: '#111',
    renderer: cleanWhite,
    supportedFormats: ['square', 'portrait', 'landscape'],
    imageSuggested: false,
    description: 'Limpo, profissional. Ideal para LinkedIn.',
  },
  {
    id: 'card-float',
    name: 'Card Float',
    category: 'minimal',
    previewGradient: 'linear-gradient(135deg, #7C3AED 0%, #06B6D4 100%)',
    previewAccent: '#fff',
    renderer: cardFloat,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: false,
    description: 'Glassmorphism card sobre gradiente colorido.',
  },
  {
    id: 'data-insight',
    name: 'Data Insight',
    category: 'minimal',
    previewGradient: 'linear-gradient(135deg, #7C3AED 0%, #ffffff 40%)',
    previewAccent: '#111',
    renderer: dataInsight,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Para dados, listas e estatísticas com impacto.',
  },
  {
    id: 'minimal-dark',
    name: 'Minimal Dark',
    category: 'minimal',
    previewGradient: 'linear-gradient(135deg, #09090F 0%, #170a2e 100%)',
    previewAccent: '#94a3b8',
    renderer: minimalDark,
    supportedFormats: ['square', 'portrait', 'story', 'landscape'],
    imageSuggested: false,
    description: 'Dark clean com radial glow e texto grande.',
  },
  {
    id: 'ios-notification',
    name: 'iOS Lock',
    category: 'social',
    previewGradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a0a2a 100%)',
    previewAccent: '#fff',
    renderer: iosNotification,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: false,
    description: 'Simula notificação iOS. Alto CTR.',
  },
  {
    id: 'carousel-progress-bar',
    name: 'Carousel Progress',
    category: 'carousel',
    previewGradient: 'linear-gradient(135deg, #111827 0%, #1d4ed8 100%)',
    previewAccent: '#93C5FD',
    renderer: dataInsight,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Alias canonico para carrossel com leitura progressiva e barras numericas.',
    niche: 'carousel',
    idealFor: 'Educational thread e numbered tips',
    supportsAnimation: true,
  },
  {
    id: 'carousel-chapter-card',
    name: 'Chapter Card',
    category: 'carousel',
    previewGradient: 'linear-gradient(135deg, #09090F 0%, #312e81 100%)',
    previewAccent: '#C4B5FD',
    renderer: minimalDark,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Capitulo numerado com headline grande e continuidade visual.',
    niche: 'carousel',
    idealFor: 'Manifestos, jornadas, threads educativas',
    supportsAnimation: true,
  },
  {
    id: 'carousel-mockup-phone',
    name: 'Mockup Phone',
    category: 'carousel',
    previewGradient: 'linear-gradient(135deg, #0f172a 0%, #111827 100%)',
    previewAccent: '#F8FAFC',
    renderer: iosNotification,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: false,
    description: 'Conteudo enquadrado em linguagem de UI/mobile para retencao.',
    niche: 'carousel',
    idealFor: 'Reels cover, UI showcase, thread mobile-first',
    supportsAnimation: true,
  },
  {
    id: 'carousel-split-timeline',
    name: 'Split Timeline',
    category: 'carousel',
    previewGradient: 'linear-gradient(90deg, #0f172a 55%, #7C3AED 100%)',
    previewAccent: '#E9D5FF',
    renderer: splitStatement,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: true,
    description: 'Timeline visual em passos para antes/depois e jornadas.',
    niche: 'carousel',
    idealFor: 'Before/after, case study, roadmap',
    supportsAnimation: true,
  },
  {
    id: 'juridico-authority',
    name: 'Juridico Authority',
    category: 'niche',
    previewGradient: 'linear-gradient(135deg, #0d1117 0%, #3b2f16 100%)',
    previewAccent: '#c9a962',
    renderer: magnataSplit,
    supportedFormats: ['square', 'portrait'],
    imageSuggested: false,
    description: 'Authority dark com leitura premium para advocacia e consultoria.',
    niche: 'juridico',
    idealFor: 'Advocacia, direito do consumidor, autoridade',
  },
  {
    id: 'saude-fresh',
    name: 'Saude Fresh',
    category: 'niche',
    previewGradient: 'linear-gradient(135deg, #F3F5EF 0%, #C8F748 100%)',
    previewAccent: '#111827',
    renderer: cleanWhite,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: false,
    description: 'Visual clean e organico para clinicas, odontologia e bem-estar.',
    niche: 'saude',
    idealFor: 'Clinicas, odontologia, wellness',
  },
  {
    id: 'finance-dark-numbers',
    name: 'Finance Dark Numbers',
    category: 'niche',
    previewGradient: 'linear-gradient(135deg, #05080D 0%, #052e16 100%)',
    previewAccent: '#00FF9F',
    renderer: viralHook,
    supportedFormats: ['square', 'portrait', 'story'],
    imageSuggested: false,
    description: 'Numeros gigantes e leitura de impacto para financas e investimentos.',
    niche: 'financas',
    idealFor: 'Investimentos, cripto, dados financeiros',
    supportsAnimation: true,
  },
  {
    id: 'tech-terminal',
    name: 'Tech Terminal',
    category: 'niche',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #052e16 100%)',
    previewAccent: '#00FF41',
    renderer: minimalDark,
    supportedFormats: ['square', 'portrait', 'story', 'landscape'],
    imageSuggested: false,
    description: 'Aesthetic terminal para dev, SaaS e automacao.',
    niche: 'tech',
    idealFor: 'Developers, SaaS, automation',
    supportsAnimation: true,
  },
];

export const getTemplate = (id: string): TemplateMetadata | undefined =>
  TEMPLATE_REGISTRY.find(t => t.id === id);

export const getTemplatesByCategory = (category: string): TemplateMetadata[] =>
  TEMPLATE_REGISTRY.filter(t => t.category === category);
