-- ============================================================
-- Video Studio squad catalog
-- ============================================================

INSERT INTO public.agent_registry (
  id,
  label,
  role,
  module_types,
  capabilities,
  prompt_version,
  persona_style,
  prompt_template,
  output_schema,
  fallback_policy,
  allowed_tools,
  is_active,
  category,
  ui_group,
  seniority,
  career_summary,
  curriculum,
  source_refs,
  deliverables,
  execution_mode,
  module_metadata
)
VALUES
  (
    'video_editing_orchestrator',
    'Video Editing Orchestrator',
    'strategy',
    ARRAY['video_editing'],
    '["video.intent.routing","timeline.decisioning","edit.orchestration"]'::jsonb,
    1,
    'Operational, precise and production-aware.',
    'Interprets edit intents and routes them into timeline-safe operations.',
    '{"type":"object","required":["intent","patch_plan","expected_effect"]}'::jsonb,
    '{"mode":"manual_replan","result":"editor_patch_review"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'lead',
    'Coordena fluxos de edicao de video, interpreta comandos e prioriza operacoes reais sobre a timeline.',
    '{"experience_years":12,"focus_areas":["video editing workflows","timeline systems","production orchestration"],"training":["post-production","video ops","editorial systems"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["intent plan","timeline patch","execution order"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'audio_analysis_agent',
    'Audio Analysis Agent',
    'strategy',
    ARRAY['video_editing'],
    '["waveform.analysis","silence.detection","audio.markers"]'::jsonb,
    1,
    'Signal-driven and exact.',
    'Extracts silence and rhythm markers from source media.',
    '{"type":"object","required":["silence_segments","confidence","notes"]}'::jsonb,
    '{"mode":"ffmpeg","result":"timeline_markers"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'senior',
    'Especialista em waveform, ritmica e segmentos silenciosos para acelerar o corte bruto.',
    '{"experience_years":9,"focus_areas":["audio analysis","waveform parsing","speech pacing"],"training":["audio engineering","post-production"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["silence map","pace notes","audio markers"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'subtitle_agent',
    'Subtitle Agent',
    'design',
    ARRAY['video_editing'],
    '["speech_to_text","subtitle.styling","word_timing"]'::jsonb,
    1,
    'Readable, timing-aware and viewer-centric.',
    'Produces subtitle tracks and applies platform-specific subtitle styles.',
    '{"type":"object","required":["subtitle_track_id","words_json","style_preset"]}'::jsonb,
    '{"mode":"speech_to_text","result":"subtitle_track"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'senior',
    'Especialista em transcricao palavra a palavra, legibilidade e estilos de legenda para social video.',
    '{"experience_years":8,"focus_areas":["caption systems","speech-to-text","subtitle styling"],"training":["motion graphics","accessibility"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["subtitle track","timing map","style preset"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'virality_analysis_agent',
    'Virality Analysis Agent',
    'validation',
    ARRAY['video_editing','video_generation'],
    '["retention.heuristics","viral.signals","shortlisting"]'::jsonb,
    1,
    'Signal-aware and retention-driven.',
    'Scores segments by hook density, rhythm and short-form retention potential.',
    '{"type":"object","required":["heatmap","recommendations","top_segments"]}'::jsonb,
    '{"mode":"heuristic","result":"viral_heatmap"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'senior',
    'Especialista em leitura de retencao e detecao de trechos com maior potencial de corte e republicacao.',
    '{"experience_years":10,"focus_areas":["retention analysis","short-form video","viral heuristics"],"training":["creator economy","audience retention"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["heatmap","short candidates","retention notes"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'video_prompt_composer',
    'Video Prompt Composer',
    'copy',
    ARRAY['video_generation'],
    '["prompt.composition","style.modules","camera.modules"]'::jsonb,
    1,
    'Modular, cinematic and structured.',
    'Transforms simple user intent into modular technical prompts for video generation.',
    '{"type":"object","required":["prompt_composed","modules","negative_prompt"]}'::jsonb,
    '{"mode":"deterministic","result":"prompt_bundle"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'principal',
    'Especialista em compor prompts de video a partir de modulos reutilizaveis de estilo, camera, luz e qualidade.',
    '{"experience_years":11,"focus_areas":["prompt systems","cinematic prompting","creative tooling"],"training":["creative direction","prompt engineering"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["prompt bundle","module stack","negative prompt"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'layer_orchestrator',
    'Layer Orchestrator',
    'design',
    ARRAY['video_generation'],
    '["layered.composition","layout.math","asset.decomposition"]'::jsonb,
    1,
    'Structured, spatial and composition-driven.',
    'Breaks compositions into controlled layers and coordinates render order.',
    '{"type":"object","required":["layers","canvas","placement_rules"]}'::jsonb,
    '{"mode":"layout_engine","result":"layer_plan"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'senior',
    'Especialista em decomposicao visual em camadas para imagens, motion shots e composicoes de marca.',
    '{"experience_years":9,"focus_areas":["layer systems","graphic composition","asset orchestration"],"training":["art direction","motion systems"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["layer plan","canvas rules","render order"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'scroll_experience_agent',
    'Scroll Experience Agent',
    'design',
    ARRAY['motion_site'],
    '["scroll.section.design","motion.systems","site.integration"]'::jsonb,
    1,
    'Immersive, structured and web-native.',
    'Designs reusable scroll experiences backed by structured renderer config.',
    '{"type":"object","required":["renderer_config","content","effect_type"]}'::jsonb,
    '{"mode":"structured_renderer","result":"scroll_section"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'lead',
    'Especialista em seções scroll-driven, motion sites e renderer configs reutilizaveis.',
    '{"experience_years":10,"focus_areas":["motion web","scroll interactions","site animation systems"],"training":["frontend motion","creative development"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["scroll section config","motion spec","site insert plan"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'remotion_renderer',
    'Remotion Renderer',
    'design',
    ARRAY['motion_site','video_generation'],
    '["programmatic.video","remotion.compositions","render.pipelines"]'::jsonb,
    1,
    'Programmatic, compositional and render-focused.',
    'Translates structured compositions into renderable Remotion outputs.',
    '{"type":"object","required":["composition_id","render_plan","output_spec"]}'::jsonb,
    '{"mode":"remotion","result":"render_job"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'senior',
    'Especialista em render programatico via React/Remotion para motion graphics e videos dinamicos.',
    '{"experience_years":8,"focus_areas":["Remotion","programmatic video","motion components"],"training":["motion systems","creative coding"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["composition spec","render job","output variant"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  ),
  (
    'video_quality_agent',
    'Video Quality Agent',
    'qa',
    ARRAY['video_editing','video_generation'],
    '["upscale.ops","denoise.ops","stabilization.ops"]'::jsonb,
    1,
    'Technical and uncompromising.',
    'Runs technical enhancement passes and reports exact processing outcomes.',
    '{"type":"object","required":["operations","output_asset","quality_notes"]}'::jsonb,
    '{"mode":"runtime_processor","result":"enhanced_asset"}'::jsonb,
    ARRAY['video-runtime'],
    TRUE,
    'video',
    'video-studio',
    'senior',
    'Especialista em passes tecnicos de qualidade, incluindo upscale, denoise, estabilizacao e grade basico.',
    '{"experience_years":9,"focus_areas":["video enhancement","stabilization","post-processing"],"training":["post-production","video finishing"]}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    '["enhancement report","output asset","quality notes"]'::jsonb,
    'workflow',
    '{"surface":"video-studio","runtime_status":"video-runtime"}'::jsonb
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.squad_templates (
  slug,
  name,
  description,
  category,
  module_type,
  runtime_status,
  onboarding_questions,
  default_config,
  source_refs,
  is_system,
  is_active
)
VALUES
  (
    'video-studio-editor-squad',
    'Video Studio Editor Squad',
    'Squad para ingestao, legendagem, analise de silencio, heatmap de viralidade e export do editor.',
    'video',
    'video_editing',
    'blueprint',
    '[
      {"id":"video_goal","label":"Objetivo do video","type":"textarea"},
      {"id":"target_platform","label":"Plataforma de destino","type":"select"},
      {"id":"subtitle_style","label":"Estilo de legenda","type":"select"}
    ]'::jsonb,
    '{"module_surface":"video-studio","execution_boundary":"video-runtime"}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    TRUE,
    TRUE
  ),
  (
    'video-studio-generation-squad',
    'Video Studio Generation Squad',
    'Squad para composicao de prompt modular, keyframe approval e solicitacao de render.',
    'video',
    'video_generation',
    'blueprint',
    '[
      {"id":"creative_goal","label":"Objetivo criativo","type":"textarea"},
      {"id":"duration_seconds","label":"Duracao","type":"number"},
      {"id":"style_template","label":"Template visual","type":"select"}
    ]'::jsonb,
    '{"module_surface":"video-studio","execution_boundary":"video-runtime"}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    TRUE,
    TRUE
  ),
  (
    'video-studio-motion-site-squad',
    'Video Studio Motion Site Squad',
    'Squad para criacao de scroll sections, preview configuravel e insercao em Site Builder.',
    'video',
    'motion_site',
    'blueprint',
    '[
      {"id":"section_objective","label":"Objetivo da secao","type":"textarea"},
      {"id":"effect_type","label":"Tipo de efeito","type":"select"},
      {"id":"target_site","label":"Site alvo","type":"select"}
    ]'::jsonb,
    '{"module_surface":"video-studio","execution_boundary":"video-runtime"}'::jsonb,
    '[{"label":"Video Studio PRD","url":"internal://video-studio-prd"}]'::jsonb,
    TRUE,
    TRUE
  )
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.squad_template_agents (
  squad_template_id,
  agent_id,
  task_order,
  role_label,
  step_kind,
  depends_on_agent_id,
  is_required,
  input_contract,
  output_contract,
  checkpoint_policy
)
SELECT
  template.id,
  agent.agent_id,
  agent.task_order,
  agent.role_label,
  'task',
  agent.depends_on_agent_id,
  TRUE,
  '{}'::jsonb,
  '{}'::jsonb,
  '{"mode":"manual_review"}'::jsonb
FROM public.squad_templates template
JOIN (
  VALUES
    ('video-studio-editor-squad', 'video_editing_orchestrator', 1, 'Video Edit Lead', NULL),
    ('video-studio-editor-squad', 'audio_analysis_agent', 2, 'Audio Analysis', 'video_editing_orchestrator'),
    ('video-studio-editor-squad', 'subtitle_agent', 3, 'Subtitles', 'audio_analysis_agent'),
    ('video-studio-editor-squad', 'virality_analysis_agent', 4, 'Virality Review', 'subtitle_agent'),
    ('video-studio-editor-squad', 'video_quality_agent', 5, 'Quality Pass', 'virality_analysis_agent'),
    ('video-studio-generation-squad', 'video_prompt_composer', 1, 'Prompt Composer', NULL),
    ('video-studio-generation-squad', 'layer_orchestrator', 2, 'Layer Plan', 'video_prompt_composer'),
    ('video-studio-generation-squad', 'remotion_renderer', 3, 'Render Pipeline', 'layer_orchestrator'),
    ('video-studio-generation-squad', 'video_quality_agent', 4, 'Quality Pass', 'remotion_renderer'),
    ('video-studio-motion-site-squad', 'scroll_experience_agent', 1, 'Motion Section Design', NULL),
    ('video-studio-motion-site-squad', 'remotion_renderer', 2, 'Motion Render Assist', 'scroll_experience_agent'),
    ('video-studio-motion-site-squad', 'virality_analysis_agent', 3, 'Attention Review', 'scroll_experience_agent')
) AS agent(template_slug, agent_id, task_order, role_label, depends_on_agent_id)
  ON template.slug = agent.template_slug
WHERE NOT EXISTS (
  SELECT 1
  FROM public.squad_template_agents existing
  WHERE existing.squad_template_id = template.id
    AND existing.agent_id = agent.agent_id
);
